# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/riscyseven/Homework/CMPUT415/gazprea-nagc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/riscyseven/Homework/CMPUT415/gazprea-nagc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/riscyseven/Homework/CMPUT415/gazprea-nagc/CMakeFiles /home/riscyseven/Homework/CMPUT415/gazprea-nagc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/riscyseven/Homework/CMPUT415/gazprea-nagc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named antlr

# Build rule for target.
antlr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr
.PHONY : antlr

# fast build rule for target.
antlr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr.dir/build.make CMakeFiles/antlr.dir/build
.PHONY : antlr/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named gazc

# Build rule for target.
gazc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gazc
.PHONY : gazc

# fast build rule for target.
gazc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/gazc.dir/build.make src/CMakeFiles/gazc.dir/build
.PHONY : gazc/fast

#=============================================================================
# Target rules for targets named symlink_gazc

# Build rule for target.
symlink_gazc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symlink_gazc
.PHONY : symlink_gazc

# fast build rule for target.
symlink_gazc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/symlink_gazc.dir/build.make src/CMakeFiles/symlink_gazc.dir/build
.PHONY : symlink_gazc/fast

#=============================================================================
# Target rules for targets named gazrt

# Build rule for target.
gazrt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gazrt
.PHONY : gazrt

# fast build rule for target.
gazrt/fast:
	$(MAKE) $(MAKESILENT) -f runtime/src/CMakeFiles/gazrt.dir/build.make runtime/src/CMakeFiles/gazrt.dir/build
.PHONY : gazrt/fast

#=============================================================================
# Target rules for targets named symlink_gazrt

# Build rule for target.
symlink_gazrt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symlink_gazrt
.PHONY : symlink_gazrt

# fast build rule for target.
symlink_gazrt/fast:
	$(MAKE) $(MAKESILENT) -f runtime/src/CMakeFiles/symlink_gazrt.dir/build.make runtime/src/CMakeFiles/symlink_gazrt.dir/build
.PHONY : symlink_gazrt/fast

gen/gazprea/GazpreaBaseListener.o: gen/gazprea/GazpreaBaseListener.cpp.o
.PHONY : gen/gazprea/GazpreaBaseListener.o

# target to build an object file
gen/gazprea/GazpreaBaseListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseListener.cpp.o
.PHONY : gen/gazprea/GazpreaBaseListener.cpp.o

gen/gazprea/GazpreaBaseListener.i: gen/gazprea/GazpreaBaseListener.cpp.i
.PHONY : gen/gazprea/GazpreaBaseListener.i

# target to preprocess a source file
gen/gazprea/GazpreaBaseListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseListener.cpp.i
.PHONY : gen/gazprea/GazpreaBaseListener.cpp.i

gen/gazprea/GazpreaBaseListener.s: gen/gazprea/GazpreaBaseListener.cpp.s
.PHONY : gen/gazprea/GazpreaBaseListener.s

# target to generate assembly for a file
gen/gazprea/GazpreaBaseListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseListener.cpp.s
.PHONY : gen/gazprea/GazpreaBaseListener.cpp.s

gen/gazprea/GazpreaBaseVisitor.o: gen/gazprea/GazpreaBaseVisitor.cpp.o
.PHONY : gen/gazprea/GazpreaBaseVisitor.o

# target to build an object file
gen/gazprea/GazpreaBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseVisitor.cpp.o
.PHONY : gen/gazprea/GazpreaBaseVisitor.cpp.o

gen/gazprea/GazpreaBaseVisitor.i: gen/gazprea/GazpreaBaseVisitor.cpp.i
.PHONY : gen/gazprea/GazpreaBaseVisitor.i

# target to preprocess a source file
gen/gazprea/GazpreaBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseVisitor.cpp.i
.PHONY : gen/gazprea/GazpreaBaseVisitor.cpp.i

gen/gazprea/GazpreaBaseVisitor.s: gen/gazprea/GazpreaBaseVisitor.cpp.s
.PHONY : gen/gazprea/GazpreaBaseVisitor.s

# target to generate assembly for a file
gen/gazprea/GazpreaBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaBaseVisitor.cpp.s
.PHONY : gen/gazprea/GazpreaBaseVisitor.cpp.s

gen/gazprea/GazpreaLexer.o: gen/gazprea/GazpreaLexer.cpp.o
.PHONY : gen/gazprea/GazpreaLexer.o

# target to build an object file
gen/gazprea/GazpreaLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaLexer.cpp.o
.PHONY : gen/gazprea/GazpreaLexer.cpp.o

gen/gazprea/GazpreaLexer.i: gen/gazprea/GazpreaLexer.cpp.i
.PHONY : gen/gazprea/GazpreaLexer.i

# target to preprocess a source file
gen/gazprea/GazpreaLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaLexer.cpp.i
.PHONY : gen/gazprea/GazpreaLexer.cpp.i

gen/gazprea/GazpreaLexer.s: gen/gazprea/GazpreaLexer.cpp.s
.PHONY : gen/gazprea/GazpreaLexer.s

# target to generate assembly for a file
gen/gazprea/GazpreaLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaLexer.cpp.s
.PHONY : gen/gazprea/GazpreaLexer.cpp.s

gen/gazprea/GazpreaListener.o: gen/gazprea/GazpreaListener.cpp.o
.PHONY : gen/gazprea/GazpreaListener.o

# target to build an object file
gen/gazprea/GazpreaListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaListener.cpp.o
.PHONY : gen/gazprea/GazpreaListener.cpp.o

gen/gazprea/GazpreaListener.i: gen/gazprea/GazpreaListener.cpp.i
.PHONY : gen/gazprea/GazpreaListener.i

# target to preprocess a source file
gen/gazprea/GazpreaListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaListener.cpp.i
.PHONY : gen/gazprea/GazpreaListener.cpp.i

gen/gazprea/GazpreaListener.s: gen/gazprea/GazpreaListener.cpp.s
.PHONY : gen/gazprea/GazpreaListener.s

# target to generate assembly for a file
gen/gazprea/GazpreaListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaListener.cpp.s
.PHONY : gen/gazprea/GazpreaListener.cpp.s

gen/gazprea/GazpreaParser.o: gen/gazprea/GazpreaParser.cpp.o
.PHONY : gen/gazprea/GazpreaParser.o

# target to build an object file
gen/gazprea/GazpreaParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaParser.cpp.o
.PHONY : gen/gazprea/GazpreaParser.cpp.o

gen/gazprea/GazpreaParser.i: gen/gazprea/GazpreaParser.cpp.i
.PHONY : gen/gazprea/GazpreaParser.i

# target to preprocess a source file
gen/gazprea/GazpreaParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaParser.cpp.i
.PHONY : gen/gazprea/GazpreaParser.cpp.i

gen/gazprea/GazpreaParser.s: gen/gazprea/GazpreaParser.cpp.s
.PHONY : gen/gazprea/GazpreaParser.s

# target to generate assembly for a file
gen/gazprea/GazpreaParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaParser.cpp.s
.PHONY : gen/gazprea/GazpreaParser.cpp.s

gen/gazprea/GazpreaVisitor.o: gen/gazprea/GazpreaVisitor.cpp.o
.PHONY : gen/gazprea/GazpreaVisitor.o

# target to build an object file
gen/gazprea/GazpreaVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaVisitor.cpp.o
.PHONY : gen/gazprea/GazpreaVisitor.cpp.o

gen/gazprea/GazpreaVisitor.i: gen/gazprea/GazpreaVisitor.cpp.i
.PHONY : gen/gazprea/GazpreaVisitor.i

# target to preprocess a source file
gen/gazprea/GazpreaVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaVisitor.cpp.i
.PHONY : gen/gazprea/GazpreaVisitor.cpp.i

gen/gazprea/GazpreaVisitor.s: gen/gazprea/GazpreaVisitor.cpp.s
.PHONY : gen/gazprea/GazpreaVisitor.s

# target to generate assembly for a file
gen/gazprea/GazpreaVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/gen/gazprea/GazpreaVisitor.cpp.s
.PHONY : gen/gazprea/GazpreaVisitor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... antlr"
	@echo "... intrinsics_gen"
	@echo "... symlink_gazc"
	@echo "... symlink_gazrt"
	@echo "... gazc"
	@echo "... gazrt"
	@echo "... parser"
	@echo "... gen/gazprea/GazpreaBaseListener.o"
	@echo "... gen/gazprea/GazpreaBaseListener.i"
	@echo "... gen/gazprea/GazpreaBaseListener.s"
	@echo "... gen/gazprea/GazpreaBaseVisitor.o"
	@echo "... gen/gazprea/GazpreaBaseVisitor.i"
	@echo "... gen/gazprea/GazpreaBaseVisitor.s"
	@echo "... gen/gazprea/GazpreaLexer.o"
	@echo "... gen/gazprea/GazpreaLexer.i"
	@echo "... gen/gazprea/GazpreaLexer.s"
	@echo "... gen/gazprea/GazpreaListener.o"
	@echo "... gen/gazprea/GazpreaListener.i"
	@echo "... gen/gazprea/GazpreaListener.s"
	@echo "... gen/gazprea/GazpreaParser.o"
	@echo "... gen/gazprea/GazpreaParser.i"
	@echo "... gen/gazprea/GazpreaParser.s"
	@echo "... gen/gazprea/GazpreaVisitor.o"
	@echo "... gen/gazprea/GazpreaVisitor.i"
	@echo "... gen/gazprea/GazpreaVisitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

